# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: help.checkmy.ws
description: site de support de Check my Website
author:
  name: Check my Website
  email: help@checkmy.ws

support_email: help@checkmy.ws

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

#include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: none
paginate: 12
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet

redcarpet:
  extensions: ['fenced_code_blocks', 'smart', 'tables', 'footnotes']

#markdown: pandoc

#pandoc:
#  format: html5
#  extensions: [smart, mathjax, section-divs]

highlighter: null

collections:
  faqs:
    output: false
  api:
    output: true
  howtos:
    output: true
  console:
    output: true

gems:
  - jekyll-sitemap
# - jekyll-pandoc